import os

path = r'd:\edgeclaw_desktop\src\ai.rs'
with open(path, 'r', encoding='utf-8', errors='ignore') as f:
    lines = f.readlines()

new_lines = []
skip = False
for line in lines:
    if 'fn parse_windows_command' in line:
        skip = True
        # Insert fixed windows parser
        new_lines.append('    #[cfg(target_os = "windows")]\n')
        new_lines.append('    fn parse_windows_command(\n')
        new_lines.append('        cmd: &str,\n')
        new_lines.append('        arg1: &str,\n')
        new_lines.append('        arg2: &str,\n')
        new_lines.append('        _raw: &str,\n')
        new_lines.append('    ) -> Option<ParsedIntent> {\n')
        new_lines.append('        match cmd {\n')
        new_lines.append('            "status" | "상태" => Some(ParsedIntent {\n')
        new_lines.append('                capability: "status_query".to_string(),\n')
        new_lines.append('                command: "systeminfo | findstr /B /C:\\"OS Name\\" /C:\\"OS Version\\" /C:\\"System Type\\" /C:\\"Total Physical\\"".to_string(),\n')
        new_lines.append('                args: vec![],\n')
        new_lines.append('                needs_confirmation: false,\n')
        new_lines.append('            }),\n')
        new_lines.append('            "cpu" | "cpu사용량" => Some(ParsedIntent {\n')
        new_lines.append('                capability: "system_info".to_string(),\n')
        new_lines.append('                command: "wmic cpu get loadpercentage,name /format:list".to_string(),\n')
        new_lines.append('                args: vec![],\n')
        new_lines.append('                needs_confirmation: false,\n')
        new_lines.append('            }),\n')
        new_lines.append('            "memory" | "메모리" | "ram" => Some(ParsedIntent {\n')
        new_lines.append('                capability: "system_info".to_string(),\n')
        new_lines.append('                command: "powershell -Command \\"Get-CimInstance Win32_OperatingSystem | Select-Object TotalVisibleMemorySize,FreePhysicalMemory | Format-List\\"".to_string(),\n')
        new_lines.append('                args: vec![],\n')
        new_lines.append('                needs_confirmation: false,\n')
        new_lines.append('            }),\n')
        new_lines.append('            "disk" | "디스크" => Some(ParsedIntent {\n')
        new_lines.append('                capability: "system_info".to_string(),\n')
        new_lines.append('                command: "powershell -Command \\"Get-PSDrive -PSProvider FileSystem | Format-Table Name,Used,Free,@{N=\'Total\';E={$_.Used+$_.Free}} -AutoSize\\"".to_string(),\n')
        new_lines.append('                args: vec![],\n')
        new_lines.append('                needs_confirmation: false,\n')
        new_lines.append('            }),\n')
        new_lines.append('            "ps" | "process" | "프로세스" => Some(ParsedIntent {\n')
        new_lines.append('                capability: "process_manage".to_string(),\n')
        new_lines.append('                command: "powershell -Command \\"Get-Process | Sort-Object CPU -Descending | Select-Object -First 20 Name,Id,CPU,WorkingSet64 | Format-Table -AutoSize\\"".to_string(),\n')
        new_lines.append('                args: vec![],\n')
        new_lines.append('                needs_confirmation: false,\n')
        new_lines.append('            }),\n')
        new_lines.append('            "network" | "네트워크" | "ip" => Some(ParsedIntent {\n')
        new_lines.append('                capability: "network_scan".to_string(),\n')
        new_lines.append('                command: "ipconfig /all".to_string(),\n')
        new_lines.append('                args: vec![],\n')
        new_lines.append('                needs_confirmation: false,\n')
        new_lines.append('            }),\n')
        new_lines.append('            "port" | "포트" | "ports" => Some(ParsedIntent {\n')
        new_lines.append('                capability: "network_scan".to_string(),\n')
        new_lines.append('                command: "netstat -an | findstr LISTENING".to_string(),\n')
        new_lines.append('                args: vec![],\n')
        new_lines.append('                needs_confirmation: false,\n')
        new_lines.append('            }),\n')
        new_lines.append('            "uptime" | "가동시간" => Some(ParsedIntent {\n')
        new_lines.append('                capability: "system_info".to_string(),\n')
        new_lines.append('                command: "powershell -Command \\"(Get-Date) - (Get-CimInstance Win32_OperatingSystem).LastBootUpTime | Select-Object Days,Hours,Minutes | Format-List\\"".to_string(),\n')
        new_lines.append('                args: vec![],\n')
        new_lines.append('                needs_confirmation: false,\n')
        new_lines.append('            }),\n')
        new_lines.append('            "services" | "서비스" | "service" => Some(ParsedIntent {\n')
        new_lines.append('                capability: "status_query".to_string(),\n')
        new_lines.append('                command: "powershell -Command \\"Get-Service | Where-Object {$_.Status -eq \'Running\'} | Select-Object -First 30 Name,DisplayName,Status | Format-Table -AutoSize\\"".to_string(),\n')
        new_lines.append('                args: vec![],\n')
        new_lines.append('                needs_confirmation: false,\n')
        new_lines.append('            }),\n')
        new_lines.append('            "restart" | "재시작" => {\n')
        new_lines.append('                if arg1.is_empty() { return None; }\n')
        new_lines.append('                Some(ParsedIntent {\n')
        new_lines.append('                    capability: "shell_exec".to_string(),\n')
        new_lines.append('                    command: format!("powershell -Command \\"Restart-Service -Name \'{}\' -Force\\"", arg1),\n')
        new_lines.append('                    args: vec![],\n')
        new_lines.append('                    needs_confirmation: true,\n')
        new_lines.append('                })\n')
        new_lines.append('            }\n')
        new_lines.append('            "stop" | "중지" => {\n')
        new_lines.append('                if arg1.is_empty() { return None; }\n')
        new_lines.append('                Some(ParsedIntent {\n')
        new_lines.append('                    capability: "shell_exec".to_string(),\n')
        new_lines.append('                    command: format!("powershell -Command \\"Stop-Service -Name \'{}\' -Force\\"", arg1),\n')
        new_lines.append('                    args: vec![],\n')
        new_lines.append('                    needs_confirmation: true,\n')
        new_lines.append('                })\n')
        new_lines.append('            }\n')
        new_lines.append('            "start" if !arg1.is_empty() => Some(ParsedIntent {\n')
        new_lines.append('                capability: "shell_exec".to_string(),\n')
        new_lines.append('                command: format!("powershell -Command \\"Start-Service -Name \'{}\'\\"", arg1),\n')
        new_lines.append('                args: vec![],\n')
        new_lines.append('                needs_confirmation: true,\n')
        new_lines.append('            }),\n')
        new_lines.append('            "kill" => {\n')
        new_lines.append('                if arg1.is_empty() { return None; }\n')
        new_lines.append('                Some(ParsedIntent {\n')
        new_lines.append('                    capability: "process_manage".to_string(),\n')
        new_lines.append('                    command: format!("taskkill /F /PID {}", arg1),\n')
        new_lines.append('                    args: vec![],\n')
        new_lines.append('                    needs_confirmation: true,\n')
        new_lines.append('                })\n')
        new_lines.append('            }\n')
        new_lines.append('            "ls" | "dir" | "파일" | "list" => Some(ParsedIntent {\n')
        new_lines.append('                capability: "file_read".to_string(),\n')
        new_lines.append('                command: format!("dir /B {}", if arg1.is_empty() { "." } else { arg1 }),\n')
        new_lines.append('                args: vec![],\n')
        new_lines.append('                needs_confirmation: false,\n')
        new_lines.append('            }),\n')
        new_lines.append('            "cat" | "type" | "읽기" | "read" => {\n')
        new_lines.append('                if arg1.is_empty() { return None; }\n')
        new_lines.append('                Some(ParsedIntent {\n')
        new_lines.append('                    capability: "file_read".to_string(),\n')
        new_lines.append('                    command: format!("type \\"{}\\"", arg1),\n')
        new_lines.append('                    args: vec![],\n')
        new_lines.append('                    needs_confirmation: false,\n')
        new_lines.append('                })\n')
        new_lines.append('            }\n')
        new_lines.append('            "find" | "search" | "검색" => {\n')
        new_lines.append('                if arg1.is_empty() { return None; }\n')
        new_lines.append('                Some(ParsedIntent {\n')
        new_lines.append('                    capability: "file_read".to_string(),\n')
        new_lines.append('                    command: format!("powershell -Command \\"Get-ChildItem -Recurse -Filter \'*{}*\' | Select-Object FullName\\"", arg1),\n')
        new_lines.append('                    args: vec![],\n')
        new_lines.append('                    needs_confirmation: false,\n')
        new_lines.append('                })\n')
        new_lines.append('            }\n')
        new_lines.append('            "log" | "logs" | "로그" => Some(ParsedIntent {\n')
        new_lines.append('                capability: "log_read".to_string(),\n')
        new_lines.append('                command: format!(\n')
        new_lines.append('                    "powershell -Command \\"Get-EventLog -LogName {} -Newest 30 | Format-Table TimeGenerated,EntryType,Message -AutoSize\\"",\n')
        new_lines.append('                    if arg1.is_empty() { "System" } else { arg1 }\n')
        new_lines.append('                ),\n')
        new_lines.append('                args: vec![],\n')
        new_lines.append('                needs_confirmation: false,\n')
        new_lines.append('            }),\n')
        new_lines.append('            "errors" | "에러" | "오류" => Some(ParsedIntent {\n')
        new_lines.append('                capability: "log_read".to_string(),\n')
        new_lines.append('                command: "powershell -Command \\"Get-EventLog -LogName Application -EntryType Error -Newest 20 | Format-Table TimeGenerated,Source,Message -AutoSize\\"".to_string(),\n')
        new_lines.append('                args: vec![],\n')
        new_lines.append('                needs_confirmation: false,\n')
        new_lines.append('            }),\n')
        new_lines.append('            "docker" => match arg1 {\n')
        new_lines.append('                "ps" | "list" | "" => Some(ParsedIntent {\n')
        new_lines.append('                    capability: "docker_manage".to_string(),\n')
        new_lines.append('                    command: "docker ps --format \\"table {{.Names}}\\t{{.Status}}\\t{{.Ports}}\\"".to_string(),\n')
        new_lines.append('                    args: vec![],\n')
        new_lines.append('                    needs_confirmation: false,\n')
        new_lines.append('                }),\n')
        new_lines.append('                "images" => Some(ParsedIntent {\n')
        new_lines.append('                    capability: "docker_manage".to_string(),\n')
        new_lines.append('                    command: "docker images --format \\"table {{.Repository}}\\t{{.Tag}}\\t{{.Size}}\\"".to_string(),\n')
        new_lines.append('                    args: vec![],\n')
        new_lines.append('                    needs_confirmation: false,\n')
        new_lines.append('                }),\n')
        new_lines.append('                "logs" => Some(ParsedIntent {\n')
        new_lines.append('                    capability: "docker_manage".to_string(),\n')
        new_lines.append('                    command: format!("docker logs --tail 50 {}", arg2),\n')
        new_lines.append('                    args: vec![],\n')
        new_lines.append('                    needs_confirmation: false,\n')
        new_lines.append('                }),\n')
        new_lines.append('                "restart" => Some(ParsedIntent {\n')
        new_lines.append('                    capability: "docker_manage".to_string(),\n')
        new_lines.append('                    command: format!("docker restart {}", arg2),\n')
        new_lines.append('                    args: vec![],\n')
        new_lines.append('                    needs_confirmation: true,\n')
        new_lines.append('                }),\n')
        new_lines.append('                "stop" => Some(ParsedIntent {\n')
        new_lines.append('                    capability: "docker_manage".to_string(),\n')
        new_lines.append('                    command: format!("docker stop {}", arg2),\n')
        new_lines.append('                    args: vec![],\n')
        new_lines.append('                    needs_confirmation: true,\n')
        new_lines.append('                }),\n')
        new_lines.append('                "start" => Some(ParsedIntent {\n')
        new_lines.append('                    capability: "docker_manage".to_string(),\n')
        new_lines.append('                    command: format!("docker start {}", arg2),\n')
        new_lines.append('                    args: vec![],\n')
        new_lines.append('                    needs_confirmation: true,\n')
        new_lines.append('                }),\n')
        new_lines.append('                "stats" => Some(ParsedIntent {\n')
        new_lines.append('                    capability: "docker_manage".to_string(),\n')
        new_lines.append('                    command: "docker stats --no-stream --format \\"table {{.Names}}\\t{{.CPUPerc}}\\t{{.MemUsage}}\\"".to_string(),\n')
        new_lines.append('                    args: vec![],\n')
        new_lines.append('                    needs_confirmation: false,\n')
        new_lines.append('                }),\n')
        new_lines.append('                _ => None,\n')
        new_lines.append('            },\n')
        new_lines.append('            "git" => match arg1 {\n')
        new_lines.append('                "status" | "" => Some(ParsedIntent {\n')
        new_lines.append('                    capability: "shell_exec".to_string(),\n')
        new_lines.append('                    command: "git status".to_string(),\n')
        new_lines.append('                    args: vec![],\n')
        new_lines.append('                    needs_confirmation: false,\n')
        new_lines.append('                }),\n')
        new_lines.append('                "log" => Some(ParsedIntent {\n')
        new_lines.append('                    capability: "shell_exec".to_string(),\n')
        new_lines.append('                    command: "git log --oneline -20".to_string(),\n')
        new_lines.append('                    args: vec![],\n')
        new_lines.append('                    needs_confirmation: false,\n')
        new_lines.append('                }),\n')
        new_lines.append('                "branch" | "branches" => Some(ParsedIntent {\n')
        new_lines.append('                    capability: "shell_exec".to_string(),\n')
        new_lines.append('                    command: "git branch -a".to_string(),\n')
        new_lines.append('                    args: vec![],\n')
        new_lines.append('                    needs_confirmation: false,\n')
        new_lines.append('                }),\n')
        new_lines.append('                "pull" => Some(ParsedIntent {\n')
        new_lines.append('                    capability: "shell_exec".to_string(),\n')
        new_lines.append('                    command: "git pull".to_string(),\n')
        new_lines.append('                    args: vec![],\n')
        new_lines.append('                    needs_confirmation: true,\n')
        new_lines.append('                }),\n')
        new_lines.append('                "push" => Some(ParsedIntent {\n')
        new_lines.append('                    capability: "shell_exec".to_string(),\n')
        new_lines.append('                    command: "git push".to_string(),\n')
        new_lines.append('                    args: vec![],\n')
        new_lines.append('                    needs_confirmation: true,\n')
        new_lines.append('                }),\n')
        new_lines.append('                "diff" => Some(ParsedIntent {\n')
        new_lines.append('                    capability: "shell_exec".to_string(),\n')
        new_lines.append('                    command: "git diff --stat".to_string(),\n')
        new_lines.append('                    args: vec![],\n')
        new_lines.append('                    needs_confirmation: false,\n')
        new_lines.append('                }),\n')
        new_lines.append('                "stash" => Some(ParsedIntent {\n')
        new_lines.append('                    capability: "shell_exec".to_string(),\n')
        new_lines.append('                    command: if arg2.is_empty() { "git stash list".to_string() } else { format!("git stash {}", arg2) },\n')
        new_lines.append('                    args: vec![],\n')
        new_lines.append('                    needs_confirmation: arg2 == "pop" || arg2 == "drop",\n')
        new_lines.append('                }),\n')
        new_lines.append('                _ => None,\n')
        new_lines.append('            },\n')
        new_lines.append('            "build" | "빌드" => Some(ParsedIntent {\n')
        new_lines.append('                capability: "shell_exec".to_string(),\n')
        new_lines.append('                command: if arg1.is_empty() {\n')
        new_lines.append('                    "cargo build 2>&1".to_string()\n')
        new_lines.append('                } else {\n')
        new_lines.append('                    format!("cargo build --{} 2>&1", arg1)\n')
        new_lines.append('                },\n')
        new_lines.append('                args: vec![],\n')
        new_lines.append('                needs_confirmation: false,\n')
        new_lines.append('            }),\n')
        new_lines.append('            "test" | "테스트" => Some(ParsedIntent {\n')
        new_lines.append('                capability: "shell_exec".to_string(),\n')
        new_lines.append('                command: if arg1.is_empty() {\n')
        new_lines.append('                    "cargo test 2>&1".to_string()\n')
        new_lines.append('                } else {\n')
        new_lines.append('                    format!("cargo test {} 2>&1", arg1)\n')
        new_lines.append('                },\n')
        new_lines.append('                args: vec![],\n')
        new_lines.append('                needs_confirmation: false,\n')
        new_lines.append('            }),\n')
        new_lines.append('            "lint" | "clippy" | "린트" => Some(ParsedIntent {\n')
        new_lines.append('                capability: "shell_exec".to_string(),\n')
        new_lines.append('                command: "cargo clippy --all-targets -- -D warnings 2>&1".to_string(),\n')
        new_lines.append('                args: vec![],\n')
        new_lines.append('                needs_confirmation: false,\n')
        new_lines.append('            }),\n')
        new_lines.append('            "fmt" | "포맷" => Some(ParsedIntent {\n')
        new_lines.append('                capability: "shell_exec".to_string(),\n')
        new_lines.append('                command: "cargo fmt 2>&1".to_string(),\n')
        new_lines.append('                args: vec![],\n')
        new_lines.append('                needs_confirmation: false,\n')
        new_lines.append('            }),\n')
        new_lines.append('            "deploy" | "배포" => Some(ParsedIntent {\n')
        new_lines.append('                capability: "shell_exec".to_string(),\n')
        new_lines.append('                command: "cargo build --release 2>&1".to_string(),\n')
        new_lines.append('                args: vec![],\n')
        new_lines.append('                needs_confirmation: true,\n')
        new_lines.append('            }),\n')
        new_lines.append('            "deps" | "audit" | "보안" => Some(ParsedIntent {\n')
        new_lines.append('                capability: "shell_exec".to_string(),\n')
        new_lines.append('                command: "cargo audit".to_string(),\n')
        new_lines.append('                args: vec![],\n')
        new_lines.append('                needs_confirmation: false,\n')
        new_lines.append('            }),\n')
        new_lines.append('            "npm" => Some(ParsedIntent {\n')
        new_lines.append('                capability: "shell_exec".to_string(),\n')
        new_lines.append('                command: format!("npm {} 2>&1", arg1),\n')
        new_lines.append('                args: vec![],\n')
        new_lines.append('                needs_confirmation: arg1 == "install" || arg1 == "ci",\n')
        new_lines.append('            }),\n')
        new_lines.append('            "db" => match arg1 {\n')
        new_lines.append('                "backup" => Some(ParsedIntent {\n')
        new_lines.append('                    capability: "shell_exec".to_string(),\n')
        new_lines.append('                    command: "echo \'Starting DB Backup...\' && pg_dump -U postgres edgeclaw > backup.sql".to_string(),\n')
        new_lines.append('                    args: vec![],\n')
        new_lines.append('                    needs_confirmation: true,\n')
        new_lines.append('                }),\n')
        new_lines.append('                "size" => Some(ParsedIntent {\n')
        new_lines.append('                    capability: "status_query".to_string(),\n')
        new_lines.append('                    command: "psql -U postgres -d edgeclaw -c \\"SELECT pg_size_pretty(pg_database_size(\'edgeclaw\'));\\"".to_string(),\n')
        new_lines.append('                    args: vec![],\n')
        new_lines.append('                    needs_confirmation: false,\n')
        new_lines.append('                }),\n')
        new_lines.append('                "connections" => Some(ParsedIntent {\n')
        new_lines.append('                    capability: "status_query".to_string(),\n')
        new_lines.append('                    command: "psql -U postgres -d edgeclaw -c \\"SELECT count(*) FROM pg_stat_activity;\\"".to_string(),\n')
        new_lines.append('                    args: vec![],\n')
        new_lines.append('                    needs_confirmation: false,\n')
        new_lines.append('                }),\n')
        new_lines.append('                _ => None,\n')
        new_lines.append('            },\n')
        new_lines.append('            "report" | "보고서" | "리포트" => Some(ParsedIntent {\n')
        new_lines.append('                capability: "shell_exec".to_string(),\n')
        new_lines.append('                command: format!(\n')
        new_lines.append('                    "powershell -Command \\"$d = Get-Date -Format \'yyyy-MM-dd\'; echo \'=== {} Report ($d) ===\'; echo \'Generating...\'\\"",\n')
        new_lines.append('                    if arg1.is_empty() { "Daily" } else { arg1 }\n')
        new_lines.append('                ),\n')
        new_lines.append('                args: vec![],\n')
        new_lines.append('                needs_confirmation: false,\n')
        new_lines.append('            }),\n')
        new_lines.append('            "analytics" | "분석" => Some(ParsedIntent {\n')
        new_lines.append('                capability: "status_query".to_string(),\n')
        new_lines.append('                command: "echo \'Analytics module not yet configured -- use system monitoring or install an analytics plugin\'".to_string(),\n')
        new_lines.append('                args: vec![],\n')
        new_lines.append('                needs_confirmation: false,\n')
        new_lines.append('            }),\n')
        new_lines.append('            "campaign" | "캠페인" => match arg1 {\n')
        new_lines.append('                "list" | "" => Some(ParsedIntent {\n')
        new_lines.append('                    capability: "status_query".to_string(),\n')
        new_lines.append('                    command: "echo \'Campaign management not yet configured -- install a marketing plugin to enable\'".to_string(),\n')
        new_lines.append('                    args: vec![], needs_confirmation: false,\n')
        new_lines.append('                }),\n')
        new_lines.append('                "status" => Some(ParsedIntent {\n')
        new_lines.append('                    capability: "status_query".to_string(),\n')
        new_lines.append('                    command: format!("echo \'Campaign status for: {}\'", arg2),\n')
        new_lines.append('                    args: vec![], needs_confirmation: false,\n')
        new_lines.append('                }),\n')
        new_lines.append('                _ => None,\n')
        new_lines.append('            },\n')
        new_lines.append('            "seo" | "검색최적화" => Some(ParsedIntent {\n')
        new_lines.append('                capability: "status_query".to_string(),\n')
        new_lines.append('                command: format!(\n')
        new_lines.append('                    "echo \'SEO analysis for: {} -- install an SEO plugin to enable\'",\n')
        new_lines.append('                    if arg1.is_empty() { "all" } else { arg1 }\n')
        new_lines.append('                ),\n')
        new_lines.append('                args: vec![],\n')
        new_lines.append('                needs_confirmation: false,\n')
        new_lines.append('            }),\n')
        new_lines.append('            "schedule" | "스케줄" | "예약" => Some(ParsedIntent {\n')
        new_lines.append('                capability: "shell_exec".to_string(),\n')
        new_lines.append('                command: "powershell -Command \\"Get-ScheduledTask | Where-Object {$_.State -eq \'Ready\'} | Select-Object -First 20 TaskName,State,LastRunTime | Format-Table -AutoSize\\"".to_string(),\n')
        new_lines.append('                args: vec![],\n')
        new_lines.append('                needs_confirmation: false,\n')
        new_lines.append('            }),\n')
        new_lines.append('            "backup" | "백업" => Some(ParsedIntent {\n')
        new_lines.append('                capability: "shell_exec".to_string(),\n')
        new_lines.append('                command: "powershell -Command \\"$ts = Get-Date -Format \'yyyyMMdd_HHmmss\'; echo \'=== Backup Started ($ts) ===\'; echo \'Configure backup targets in agent.toml [backup] section\'\\"".to_string(),\n')
        new_lines.append('                args: vec![],\n')
        new_lines.append('                needs_confirmation: true,\n')
        new_lines.append('            }),\n')
        new_lines.append('            "ping" => Some(ParsedIntent {\n')
        new_lines.append('                capability: "network_scan".to_string(),\n')
        new_lines.append('                command: format!("ping -n 4 {}", if arg1.is_empty() { "google.com" } else { arg1 }),\n')
        new_lines.append('                args: vec![],\n')
        new_lines.append('                needs_confirmation: false,\n')
        new_lines.append('            }),\n')
        new_lines.append('            "env" | "환경" => Some(ParsedIntent {\n')
        new_lines.append('                capability: "system_info".to_string(),\n')
        new_lines.append('                command: "set".to_string(),\n')
        new_lines.append('                args: vec![],\n')
        new_lines.append('                needs_confirmation: false,\n')
        new_lines.append('            }),\n')
        new_lines.append('            "whoami" => Some(ParsedIntent {\n')
        new_lines.append('                capability: "system_info".to_string(),\n')
        new_lines.append('                command: "whoami /all".to_string(),\n')
        new_lines.append('                args: vec![],\n')
        new_lines.append('                needs_confirmation: false,\n')
        new_lines.append('            }),\n')
        new_lines.append('            "help" | "도움말" | "명령어" => Some(ParsedIntent {\n')
        new_lines.append('                capability: "status_query".to_string(),\n')
        new_lines.append('                command: "echo \'=== EdgeClaw Commands ===\' && echo. && echo [System] status, cpu, memory, disk, ps, network, port, uptime, services && echo [Files] ls, cat, find, log, errors && echo [DevOps] docker ps/logs/restart, git status/log/pull/push && echo [Build] build, test, lint, fmt, deploy, deps, audit && echo [Node] npm test/build/start/audit/outdated && echo [DB] db backup/size/connections && echo [Marketing] report, analytics, campaign, seo, schedule && echo [Misc] ping, env, whoami, backup, help".to_string(),\n')
        new_lines.append('                args: vec![],\n')
        new_lines.append('                needs_confirmation: false,\n')
        new_lines.append('            }),\n')
        new_lines.append('            _ => None,\n')
        new_lines.append('        }\n')
        new_lines.append('    }\n')
    elif 'fn parse_linux_command' in line:
        skip = True
        new_lines.append('    #[cfg(not(target_os = "windows"))]\n')
        new_lines.append('    fn parse_linux_command(cmd: &str, arg1: &str, arg2: &str, _raw: &str) -> Option<ParsedIntent> {\n')
        new_lines.append('        match cmd {\n')
        new_lines.append('            "status" | "상태" => Some(ParsedIntent {\n')
        new_lines.append('                capability: "status_query".to_string(),\n')
        new_lines.append('                command: "uname -a && uptime && free -h | head -2".to_string(),\n')
        new_lines.append('                args: vec![], needs_confirmation: false,\n')
        new_lines.append('            }),\n')
        new_lines.append('            "cpu" | "cpu사용량" => Some(ParsedIntent {\n')
        new_lines.append('                capability: "system_info".to_string(),\n')
        new_lines.append('                command: "top -bn1 | head -20".to_string(),\n')
        new_lines.append('                args: vec![], needs_confirmation: false,\n')
        new_lines.append('            }),\n')
        new_lines.append('            "memory" | "메모리" | "ram" => Some(ParsedIntent {\n')
        new_lines.append('                capability: "system_info".to_string(),\n')
        new_lines.append('                command: "free -h".to_string(),\n')
        new_lines.append('                args: vec![], needs_confirmation: false,\n')
        new_lines.append('            }),\n')
        new_lines.append('            "disk" | "디스크" => Some(ParsedIntent {\n')
        new_lines.append('                capability: "system_info".to_string(),\n')
        new_lines.append('                command: "df -h".to_string(),\n')
        new_lines.append('                args: vec![], needs_confirmation: false,\n')
        new_lines.append('            }),\n')
        new_lines.append('            "ps" | "process" | "프로세스" => Some(ParsedIntent {\n')
        new_lines.append('                capability: "process_manage".to_string(),\n')
        new_lines.append('                command: "ps aux --sort=-pcpu | head -20".to_string(),\n')
        new_lines.append('                args: vec![], needs_confirmation: false,\n')
        new_lines.append('            }),\n')
        new_lines.append('            "network" | "네트워크" | "ip" => Some(ParsedIntent {\n')
        new_lines.append('                capability: "network_scan".to_string(),\n')
        new_lines.append('                command: "ip addr show || ifconfig".to_string(),\n')
        new_lines.append('                args: vec![], needs_confirmation: false,\n')
        new_lines.append('            }),\n')
        new_lines.append('            "port" | "포트" | "ports" => Some(ParsedIntent {\n')
        new_lines.append('                capability: "network_scan".to_string(),\n')
        new_lines.append('                command: "ss -tlnp".to_string(),\n')
        new_lines.append('                args: vec![], needs_confirmation: false,\n')
        new_lines.append('            }),\n')
        new_lines.append('            "services" | "서비스" | "service" => Some(ParsedIntent {\n')
        new_lines.append('                capability: "status_query".to_string(),\n')
        new_lines.append('                command: "systemctl list-units --type=service --state=running".to_string(),\n')
        new_lines.append('                args: vec![], needs_confirmation: false,\n')
        new_lines.append('            }),\n')
        new_lines.append('            "restart" | "재시작" => {\n')
        new_lines.append('                if arg1.is_empty() { return None; }\n')
        new_lines.append('                Some(ParsedIntent {\n')
        new_lines.append('                    capability: "shell_exec".to_string(),\n')
        new_lines.append('                    command: format!("systemctl restart {}", arg1),\n')
        new_lines.append('                    args: vec![], needs_confirmation: true,\n')
        new_lines.append('                })\n')
        new_lines.append('            }\n')
        new_lines.append('            "stop" | "중지" => {\n')
        new_lines.append('                if arg1.is_empty() { return None; }\n')
        new_lines.append('                Some(ParsedIntent {\n')
        new_lines.append('                    capability: "shell_exec".to_string(),\n')
        new_lines.append('                    command: format!("systemctl stop {}", arg1),\n')
        new_lines.append('                    args: vec![], needs_confirmation: true,\n')
        new_lines.append('                })\n')
        new_lines.append('            }\n')
        new_lines.append('            "start" if !arg1.is_empty() => Some(ParsedIntent {\n')
        new_lines.append('                capability: "shell_exec".to_string(),\n')
        new_lines.append('                command: format!("systemctl start {}", arg1),\n')
        new_lines.append('                args: vec![], needs_confirmation: true,\n')
        new_lines.append('            }),\n')
        new_lines.append('            "kill" => {\n')
        new_lines.append('                if arg1.is_empty() { return None; }\n')
        new_lines.append('                Some(ParsedIntent {\n')
        new_lines.append('                    capability: "process_manage".to_string(),\n')
        new_lines.append('                    command: format!("kill -9 {}", arg1),\n')
        new_lines.append('                    args: vec![], needs_confirmation: true,\n')
        new_lines.append('                })\n')
        new_lines.append('            }\n')
        new_lines.append('            "ls" | "dir" | "파일" | "list" => Some(ParsedIntent {\n')
        new_lines.append('                capability: "file_read".to_string(),\n')
        new_lines.append('                command: format!("ls -F {}", if arg1.is_empty() { "." } else { arg1 }),\n')
        new_lines.append('                args: vec![], needs_confirmation: false,\n')
        new_lines.append('            }),\n')
        new_lines.append('            "cat" | "read" | "읽기" => Some(ParsedIntent {\n')
        new_lines.append('                capability: "file_read".to_string(),\n')
        new_lines.append('                command: format!("cat \'{}\'", arg1),\n')
        new_lines.append('                args: vec![], needs_confirmation: false,\n')
        new_lines.append('            }),\n')
        new_lines.append('            "find" | "search" | "검색" => Some(ParsedIntent {\n')
        new_lines.append('                capability: "file_read".to_string(),\n')
        new_lines.append('                command: format!("find . -name \'*{}*\'", arg1),\n')
        new_lines.append('                args: vec![], needs_confirmation: false,\n')
        new_lines.append('            }),\n')
        new_lines.append('            "log" | "logs" | "로그" => Some(ParsedIntent {\n')
        new_lines.append('                capability: "log_read".to_string(),\n')
        new_lines.append('                command: "journalctl -n 50".to_string(),\n')
        new_lines.append('                args: vec![], needs_confirmation: false,\n')
        new_lines.append('            }),\n')
        new_lines.append('            "docker" => match arg1 {\n')
        new_lines.append('                "ps" | "list" | "" => Some(ParsedIntent {\n')
        new_lines.append('                    capability: "docker_manage".to_string(),\n')
        new_lines.append('                    command: "docker ps".to_string(),\n')
        new_lines.append('                    args: vec![], needs_confirmation: false,\n')
        new_lines.append('                }),\n')
        new_lines.append('                "restart" => Some(ParsedIntent {\n')
        new_lines.append('                    capability: "docker_manage".to_string(),\n')
        new_lines.append('                    command: format!("docker restart {}", arg2),\n')
        new_lines.append('                    args: vec![], needs_confirmation: true,\n')
        new_lines.append('                }),\n')
        new_lines.append('                _ => None,\n')
        new_lines.append('            },\n')
        new_lines.append('            _ => None,\n')
        new_lines.append('        }\n')
        new_lines.append('    }\n')
    elif 'fn parse_ollama_response' in line:
        skip = False
        new_lines.append(line)
    elif not skip:
        new_lines.append(line)

with open(path, 'w', encoding='utf-8') as f:
    f.writelines(new_lines)
